config/routes.rb
Rails.application.routes.draw do
  get '/rankings' => 'pages#rankings'
  get '/primary_results' => 'pages#primary_results'
  root 'pages#home'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def rankings
  end

  def primary_results
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fantasy Politics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

</head>
<body>

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
   <div class="container">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
         <%= link_to root_path, class: 'navbar-brand' do %>
            <div class="brand-style">
               <i class="fa fa-university"></i>
               Fantasy Politics
            </div>
            <% end %>
      </div>

      <div class="collapse navbar-collapse" id="main-nav-collapse">
         <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "GOP Primary Results", primary_results_path %></li>
            <li><%= link_to "Rankings", rankings_path %></li>
         </ul>

      </div><!-- /.navbar-collapse -->
   </div>
</nav>
<div class="container">
   <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
   <h1>Fantasy Politics</h1>
</div>

<br />

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h3>South Carolina Picks</h3>

      <table id="picksTable" class="table table-bordered table-condensed table-striped">
        <thead>
          <tr>
            <th>NAME</th>
            <th>GOP Picks</th>
            <th>Delete</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>

</div>

<br />
<br />
<br />

<div class="container">
   <div class="row">
      <div id="picksForm" class="well well-sm col-sm-6 col-sm-offset-3">
         <form>
           <fieldset class="form-group">
             <label for="userName">Name</label>
             <input type="text" class="form-control" id="userName" placeholder="Joe Example">
             <small class="text-muted">This is where you put YOUR name.</small>
           </fieldset>
           <fieldset class="form-group">
             <label for="gopPicks">GOP Picks</label>
             <input type="text" class="form-control" id="gopPicks" placeholder="Candidate #1 Candidate #2">
             <small class="text-muted">For now just put a space between each candidates nameas shown in the placeholder text. I'll make it cooler and more user friendly later.</small>
           </fieldset>

           <button type="button" id="updateButton" class="btn btn-success" onclick="picksUpdate();">Submit Picks</button>
         </form>
      </div>
   </div>
</div>

<script>

   // Add picks to <table>
   // function picksAdd() {
   //    // First check if a <tbody> tag exists, add one if not
   //    if($("#picksTable tbody").length == 0) {
   //       $("#picksTable").append("<tbody></tbody>");
   //    }
   //
   //     Append pick to the table
   //    $("#picksTable tbody").append(
   //       "<tr>" +
   //          "<td>Joe Example</td>" +
   //          "<td>1. Candidate #1 <br /> 2. Candidate #2</td>" +
   //       "</tr>"
   //    );
   // }

   // Add picks to table
   function picksAddToTable() {
      // First check if a <tbody> tag exists, add one if not
      if ($("#picksTable tbody").length == 0){
         $("picksTable").append("<tbody></tbody>");
      }

   // Clear form
   function formClear() {
      $("#userName").val("");
      $("#gopPicks").val("");
   }

   function pickDelete(ctl) {
      $(ctl).parents("tr").remove();
   }

      // Append picks to table
      $("#picksTable tbody").append(
         "<tr>" +
            "<td>" + $("#userName").val() + "</td>" +
            "<td>" + $("#gopPicks").val() + "</td>" +
            "<td>" + "<button type='button'" + "onclick='pickDelete(this);'" + "class='btn btn-danger'>" + "<span class='glyphicon glyphicon-remove' />" + "</button>" + "</td>" +
         "</tr>"
      );
   }


   // Button function once button is clicked
   function picksUpdate() {
      if ($("#userName").val() != null && $("#userName").val() != '') {
            // Add product to table
            pickAddToTable();
            // Clear form fields
            formClear();
            // Focus to userName field
            $("#userName").focus();
      }
   }


   $(document).ready(function() {
      picksAddToTable();
      picksUpdate();
      formClear();
      pickDelete();
   });

</script

app/views/pages/primary_results.html.erb
<div id="resultsHead" class="text-center">
   <h2>GOP Primary Results</h2>
</div>

<br />

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <table id="resultsTable" class="table table-bordered table-condensed table-striped">
        <thead>
          <!-- Column labels -->
          <tr>
            <th style="color: ">Priamry/Caucus</th>
            <th>Adam's Picks</th>
            <th>Justin's Picks</th>
            <th>Tommy's Picks</th>
            <th>Zac's Picks</th>
            <th style="color: red">Results</th>
            <th style="color: gold">POINTS AWARDED</th>
          </tr>



          <!-- Iowa Caucus -->
          <tr>
            <!-- Primary Name -->
            <td class="text-center">Iowa Caucus</td>
            <!-- Adam's Picks -->
            <td>
               1. Donald Trump
               <br />
               2. Ted Cruz
            </td>
            <!-- Justin's Picks -->
            <td>
               1. Donald Trump
               <br />
               2. Ted Cruz
            </td>
            <!-- Tommy's Picks -->
            <td>
               1. Rand Paul
               <br />
               2. Ted Cruz
            </td>
            <!-- Zac's Picks -->
            <td>
               1. Ted Cruz
               <br />
               2. Donald Trump
            </td>
            <!-- Results -->
            <td>
               1. Ted Cruz: 27.6% & 8 Delegates
               <br />
               2. Donald Trump: 24.3% & 7 Delegates
            </td>
            <!-- Points Awarded -->
            <td>
               Adam: 0
               <br />
               Justin: 0
               <br />
               Tommy: 0
               <br />
               Zac: 5

            </td>

          </tr>



          <!-- New Hampshire Primary -->
          <tr>
            <!-- Primary Name -->
            <td class="text-center">New Hampshire Primary</td>
            <!-- Adam's Picks -->
            <td>
               1. Donald Trump
               <br />
               2. Marco Rubio
            </td>
            <!-- Justin's Picks -->
            <td>
               1. Donald Trump
               <br />
               2. Marco Rubio
            </td>
            <!-- Tommy's Picks -->
            <td>
               1. Donald Trump
               <br />
               2. Marco Rubio
            </td>
            <!-- Zac's Picks -->
            <td>
               1. Donald Trump
               <br />
               2. Ted Cruz
            </td>
            <!-- Results -->
            <td>
               1. Donald Trump: 35.3% & 10 Delegates
               <br />
               2. John Kasich: 15.8% & 4 Delegates
            </td>
            <!-- Points Awarded -->
            <td>
               Adam: 3
               <br />
               Justin: 3
               <br />
               Tommy: 3
               <br />
               Zac: 3

            </td>
          </tr>



          <!-- South Carolina Primary -->
          <tr>
            <!-- Primary Name -->
            <td class="text-center">South Carolina Primary</td>
            <!-- Adam's Picks -->
            <td>
               1.
               <br />
               2.
            </td>
            <!-- Justin's Picks -->
            <td>
               1.
               <br />
               2.
            </td>
            <!-- Tommy's Picks -->
            <td>
               1.
               <br />
               2.
            </td>
            <!-- Zac's Picks -->
            <td>
               1.
               <br />
               2.
            </td>
            <!-- Results -->
            <td>
               1.
               <br />
               2.
            </td>
            <!-- Points Awarded -->
            <td>
               Adam:
               <br />
               Justin:
               <br />
               Tommy:
               <br />
               Zac:

            </td>
          </tr>



          <!-- Nevada Primary -->
          <tr>
            <!-- Primary Name -->
            <td class="text-center">Nevada Primary</td>
            <!-- Adam's Picks -->
            <td>
               1.
               <br />
               2.
            </td>
            <!-- Justin's Picks -->
            <td>
               1.
               <br />
               2.
            </td>
            <!-- Tommy's Picks -->
            <td>
               1.
               <br />
               2.
            </td>
            <!-- Zac's Picks -->
            <td>
               1.
               <br />
               2.
            </td>
            <!-- Results -->
            <td>
               1.
               <br />
               2. 
            </td>
            <!-- Points Awarded -->
            <td>
               Adam:
               <br />
               Justin:
               <br />
               Tommy:
               <br />
               Zac:

            </td>
          </tr>



        </thead>
      </table>
    </div>
  </div>

</div>

app/views/pages/rankings.html.erb
<h2>RANKINGS</h2>